### ISSUE TITLE
Nav -> UL 

### ISSUE THREAD

**Issue by tisberr** [driezie/the-client-website#2]
https://github.com/driezie/the-client-website/blob/e8d1386d85af91c1d525dbc029c4129bf8660514/index.html#L13-L22

Je maakt gebruik van een nav met 2 divjes, terwijl een UL>LI beter zou kunnen werken hier 
https://css-tricks.com/responsive-menu-concepts/

**Comment by driezie** [comment]
https://github.com/driezie/the-client-website/blob/0209e33c801bfd0bc76e4eaefbdbd20ce0c2260a/index.html#L17-L38

Ik heb hier even aan gewerkt en ik heb het veranderd zodat het nu beter staat! Bedankt!
