### ISSUE TITLE
NL?

### ISSUE THREAD

**Issue by WesleySchorel** [driezie/the-client-website#5]
De taal van de website is Nederlands. Verander "EN" naar "NL"

https://github.com/driezie/the-client-website/blob/00746dc264aca1b8705d9f9deccec9b666556901/index.html#L3C1-L3C17

**Comment by driezie** [comment]
https://github.com/driezie/the-client-website/blob/77097b88616f03be4ae7285b1415373fd3143826/index.html#L2

Ik heb dit veranderd in mijn laatste update! Bedankt voor de issue
